In [1]:
import numpy as np

In [2]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [3]:
my_list = [1,2,3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
type(np.array(my_list))

numpy.ndarray

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [11]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [12]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [13]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [18]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [19]:
np.linspace(1,10,100)

array([  1.        ,   1.09090909,   1.18181818,   1.27272727,
         1.36363636,   1.45454545,   1.54545455,   1.63636364,
         1.72727273,   1.81818182,   1.90909091,   2.        ,
         2.09090909,   2.18181818,   2.27272727,   2.36363636,
         2.45454545,   2.54545455,   2.63636364,   2.72727273,
         2.81818182,   2.90909091,   3.        ,   3.09090909,
         3.18181818,   3.27272727,   3.36363636,   3.45454545,
         3.54545455,   3.63636364,   3.72727273,   3.81818182,
         3.90909091,   4.        ,   4.09090909,   4.18181818,
         4.27272727,   4.36363636,   4.45454545,   4.54545455,
         4.63636364,   4.72727273,   4.81818182,   4.90909091,
         5.        ,   5.09090909,   5.18181818,   5.27272727,
         5.36363636,   5.45454545,   5.54545455,   5.63636364,
         5.72727273,   5.81818182,   5.90909091,   6.        ,
         6.09090909,   6.18181818,   6.27272727,   6.36363636,
         6.45454545,   6.54545455,   6.63636364,   6.72

In [20]:
np.random.rand(5)

array([ 0.57222803,  0.67528089,  0.23088758,  0.63244618,  0.08578125])

In [21]:
np.random.rand(5,5)

array([[ 0.3238651 ,  0.7918871 ,  0.2982841 ,  0.67376538,  0.87877379],
       [ 0.21186116,  0.41324306,  0.98097515,  0.88131732,  0.05634068],
       [ 0.63704626,  0.42329261,  0.22706077,  0.49287385,  0.7472091 ],
       [ 0.83773316,  0.08715592,  0.68194773,  0.3869986 ,  0.61984206],
       [ 0.99122518,  0.05238164,  0.97996244,  0.20971478,  0.87034755]])

In [22]:
np.random.randn(5,5)

array([[-0.89287351,  0.43271281, -0.20456066, -1.02415115,  0.08922332],
       [-1.39045362, -0.37981568,  0.56101023,  0.24445407,  1.20364563],
       [-0.94137148,  0.04968946,  2.05804808,  1.07219269,  0.19755082],
       [-0.78502594, -0.58038373, -0.04042344, -0.86857292, -0.9241897 ],
       [ 1.13712487,  0.95086424,  0.91243818,  0.19255367,  0.08541389]])

In [23]:
np.random.randint(5)

0

In [24]:
np.random.randint(5)

0

In [25]:
np.random.randint(5)

3

In [26]:
np.random.randint(5,10)

5

In [27]:
np.random.randint(5,10)

8

In [28]:
np.random.randint(5,10,10)

array([8, 8, 9, 5, 7, 9, 7, 9, 7, 6])

In [31]:
np.random.randint(5,10,size=10)

array([7, 5, 5, 9, 8, 8, 6, 6, 9, 9])

In [32]:
np.random.randint(5,10,size=(3,4))

array([[8, 5, 7, 9],
       [7, 8, 9, 7],
       [7, 7, 9, 9]])

In [33]:
arr = np.arange(25)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
arr.reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
arr = arr.reshape((5,5))


In [40]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
arr = arr.reshape((4,5))

ValueError: cannot reshape array of size 25 into shape (4,5)

In [42]:
arr = arr.reshape(25)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
arr.min()

0

In [45]:
arr.max()

24

In [46]:
arr.argmax()

24

In [47]:
arr.argmax

<function argmax>

In [48]:
arr.shape

(25,)

In [49]:
type(arr.shape)

tuple

In [52]:
from numpy.random import randint

In [53]:
randint(3,7,10)

array([3, 3, 5, 4, 5, 5, 3, 6, 4, 3])

In [55]:
arr = np.random.randint(0,50,25)

In [56]:
arr

array([17, 19, 39,  1, 26, 13, 32, 40, 47, 42,  3,  4, 14, 29, 20, 46, 37,
        3, 33, 12, 21, 23,  8,  9, 41])

In [57]:
arr[5]

13

In [58]:
arr[:5]

array([17, 19, 39,  1, 26])

In [59]:
arr[:5] = 100

In [60]:
arr

array([100, 100, 100, 100, 100,  13,  32,  40,  47,  42,   3,   4,  14,
        29,  20,  46,  37,   3,  33,  12,  21,  23,   8,   9,  41])

In [61]:
slice_of_arr = arr[:6]

In [62]:
slice_of_arr

array([100, 100, 100, 100, 100,  13])

In [63]:
arr[0] = 200

In [64]:
arr

array([200, 100, 100, 100, 100,  13,  32,  40,  47,  42,   3,   4,  14,
        29,  20,  46,  37,   3,  33,  12,  21,  23,   8,   9,  41])

In [65]:
slice_of_arr

array([200, 100, 100, 100, 100,  13])

In [66]:
copy_arr = slice_of_arr.copy()

In [67]:
copy_arr

array([200, 100, 100, 100, 100,  13])

In [68]:
arr[0] = 300

In [69]:
slice_of_arr

array([300, 100, 100, 100, 100,  13])

In [70]:
copy_arr

array([200, 100, 100, 100, 100,  13])

In [71]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [72]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [74]:
arr_2d[0][0]

5

In [75]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [76]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [78]:
arr_2d[1,2]

30

In [79]:
arr_2d[1][2]

30

In [80]:
arr = np.arange(1,11)

In [81]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [82]:
barr = arr > 5

In [83]:
barr


array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [84]:
arr[barr]

array([ 6,  7,  8,  9, 10])

In [85]:
arr[arr<3]

array([1, 2])

In [86]:
arr_2d = np.arange(50).reshape(5,10)

In [87]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [88]:
arr_2d[1:3,1:3]

array([[11, 12],
       [21, 22]])

# Numpy Operations

-Array with Array
-Array with Scalars
-Universal Array Functions

In [89]:
arr1 = np.arange(25).reshape(5,5)

In [90]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [91]:
arr2 = np.eye(5)

In [92]:
arr2

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [93]:
arr1 + arr2

array([[  1.,   1.,   2.,   3.,   4.],
       [  5.,   7.,   7.,   8.,   9.],
       [ 10.,  11.,  13.,  13.,  14.],
       [ 15.,  16.,  17.,  19.,  19.],
       [ 20.,  21.,  22.,  23.,  25.]])

In [96]:
arr = np.arange(11)

In [97]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [99]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [100]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [101]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [102]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [103]:
arr / arr

c:\python27\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [104]:
1 / arr

c:\python27\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.


array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [105]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [106]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [107]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [108]:
np.max(arr)

10

In [109]:
np.min(arr)

0

In [110]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [111]:
np.log(arr)

c:\python27\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])

In [112]:
np.divide(arr,arr)

c:\python27\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [115]:
type(np.true_divide(arr,arr)[0])

c:\python27\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


numpy.float64

In [116]:
import numpy as np

In [117]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [118]:
np.zeros((10,10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [119]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [120]:
np.ones(10) * 5

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [122]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [123]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [124]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [126]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [130]:
np.random.rand(1)

array([ 0.57046671])

In [132]:
np.random.randn(25)

array([ 0.92877551,  0.23035915,  0.71926421, -1.27986272, -1.52261175,
        1.0302177 , -0.60578986, -1.72123663,  1.70986129, -1.93935117,
       -0.302492  ,  0.54996958,  0.2820898 ,  0.12022089,  0.65523645,
       -0.57607933,  1.39628163,  2.2946484 , -0.55537939, -0.77060473,
       -1.6876129 , -0.38178179, -0.36551189, -0.06142341, -0.02380565])

In [141]:
np.round(np.linspace(0.01,1,100).reshape(10,10),2)

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [147]:
np.linspace(0,1,20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

In [148]:
mat = np.arange(1,26).reshape(5,5)

In [149]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [150]:
mat2 = np.arange(12,16)
np.array([mat2,mat2+5,mat2+10])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [151]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [152]:
mat[3,4]

20

In [159]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [161]:
mat[4,]

array([21, 22, 23, 24, 25])

In [162]:
mat[3:5,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [163]:
np.sum(mat)

325

In [165]:
np.std(mat)

7.2111025509279782

In [167]:
np.sum(mat,1)

array([ 15,  40,  65,  90, 115])